# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 391e21aa327b32b36764207e240c56c8fcaaada24ff94fc814461ef1526a713947a17f1e76403746060e300ea62a6f3ee6cfffe3caf2b5e9fa57378e03809eff

test:
  secret_key_base: 8b5cf9024fdb4cc06e6d5510fbe19f27a28b3eba6815188710f570b6c1a2ed76b817a6d14a1e0f4eb4c3978d15283f7223d7dcdcd69bb4c833f98ffe5feebaea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
